### ISSUE TITLE
Infof helpers

### ISSUE THREAD

**Issue by bersace** [zerodha/logf#19]
Hi,

logf looks awesome. What do you think to provide a `Infof(format, args...)` variant ? I known this API won't allow to add fields, but that may be handy to format message.

Regards,

**Comment by mr-karan** [comment]
Hey

> I known this API won't allow to add fields

Yeah, I believe to maintain consistency, it's better to not have this. 

`logf.Info(fmt.Sprintf("hello %s", "world"))` is a fair tradeoff for such scenarios. I've been using `logf` in many applications so far and have never felt the need to add formatting inside message, I usually just add extra metadata as KV pairs, so I am curious to know about your usecase.

**Comment by bersace** [comment]
It's just for some consistency `log.Printf`, I find it handy. I understand your point.
